### ISSUE TITLE
Add torch-light & crystal vanishing?

### ISSUE THREAD

**Issue by nikzaugg** [nikzaugg/PolyHunter#5]
**Todo:**
- [x] load dummy obj as the torch
- [x] create a light that is always at the position of the torch 
- [x] each frame, set torch-position to players-position (with some offset)
- [x] update all shaders to incorporate 2 light-sources (add uniforms with **_1**)
- [x] need to work with **attenuation** and **angle** of the spotlight!
- [x] add input-check for double-tap in right 10% of screen -> if double tap recognized turn on the light (set intensity to 1.0?)
- [x] if a crystal is hit by the torch-light, something happens and the crystal disappears (score changes)
- [x] replace dummy-torch with a real model

Goal
we want a torch which the player can turn on and turn off via pressing in some portion of the screen. This torch is used to highlight the world in front of the player in a cone. It will also make it easier in the beginning to spot crystals.

Implementation ideas:
- tutorial about spotlights: https://www.tomdalling.com/blog/modern-opengl/08-even-more-lighting-directional-lights-spotlights-multiple-lights/
- create a new normal light with bRenderer
- set position of the light to players position each frame (add some offset so it's more realistic)
- create a uniform with which we can control if the light is on or not (from user input)
if torch should be on set uniform variable
- make sure that all affected entities receive light details about the torch when rendered
adjust affected shaders
